name: Ultimate Gaming

on: workflow_dispatch

jobs:
  linux-gaming:
    runs-on: ubuntu-latest
    timeout-minutes: 525600

    steps:
    - name: System Update
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:graphics-drivers/ppa -y

    - name: Install NVIDIA Drivers
      run: |
        sudo apt install -y build-essential dkms
        sudo apt install -y nvidia-driver-525 nvidia-settings
        sudo systemctl enable nvidia-persistenced
        sudo systemctl start nvidia-persistenced

    - name: Install Chrome Remote Desktop
      run: |
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo apt install -y ./chrome-remote-desktop_current_amd64.deb
        sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xfce4-goodies
        sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'

    - name: Setup Gaming Environment
      run: |
        sudo apt install -y lutris wine64
        sudo apt install -y pulseaudio pavucontrol
        sudo apt install -y joystick jstest-gtk mesa-utils
        sudo apt install -y google-chrome-stable

    - name: Configure CRD Service
      run: |
        sudo systemctl enable chrome-remote-desktop@$USER
        sudo systemctl start chrome-remote-desktop@$USER
        DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="${{ github.event.inputs.crd_code }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) --pin=123456

    - name: Setup Custom User
      run: |
        sudo useradd -m -s /bin/bash droidmaster
        sudo usermod -aG sudo,audio,video droidmaster
        echo "droidmaster:Morales2009" | sudo chpasswd
        echo "droidmaster ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/droidmaster
        sudo chmod 0440 /etc/sudoers.d/droidmaster

    - name: Keep Active
      run: |
        while true; do
          echo "🎮 Gaming System Active - $(date)"
          sleep 300
        done
